// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evnotjuukxgbwhytktgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bm90anV1a3hnYndoeXRrdGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODc2ODgsImV4cCI6MjA3MTY2MzY4OH0.MiuCpi7M6NK35TUieFdwxZsZxoBCTTI8G1-gLMbTikw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});