// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxgjmupslmcugzqbusoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Z2ptdXBzbG1jdWd6cWJ1c296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDczNzcsImV4cCI6MjA3NDIyMzM3N30.Y28zmtv-KMfxa2E1c-IHR6bQgmzDaegEcuD__84vew8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});